{% set version = "1.7.1" %}
{% set name = "linbox" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/linbox-team/linbox/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: a2b5f910a54a46fa75b03f38ad603cae1afa973c95455813d85cf72c27553bd8
  patches:
    - 0001-Disable-failing-test.patch
    # Backport upstream patch to work around https://github.com/linbox-team/linbox/issues/328
    - ntl.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("linbox", "x.x") }}

requirements:
  build:
    - libtool
    - automake
    - autoconf
    - make
    - pkg-config
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - gmp
    - mpfr
    - ntl
    - libflint
    - givaro
    - iml
    - fflas-ffpack
    - m4ri
    - m4rie

test:
  commands:
    - test -f ${PREFIX}/include/linbox/integer.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]

about:
  home: http://linalg.org/
  license: LGPL-2.1-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: C++ library for exact, high-performance linear algebra
  dev_url: https://github.com/linbox-team/linbox

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
